/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContextBox: typeof import('./src/components/common/ContextBox.vue')['default']
    DailyMain: typeof import('./src/components/page/Sales/daily/DailyMain.vue')['default']
    DailySearch: typeof import('./src/components/page/Sales/daily/DailySearch.vue')['default']
    DepartmentMain: typeof import('./src/components/page/System/Department/DepartmentMain.vue')['default']
    DepartmentModal: typeof import('./src/components/page/System/Department/DepartmentModal.vue')['default']
    DepartmentSearch: typeof import('./src/components/page/System/Department/DepartmentSearch.vue')['default']
    EmployeeModal: typeof import('./src/components/page/employee/EmployeeModal.vue')['default']
    EmployeeSearchBar: typeof import('./src/components/page/employee/EmployeeSearchBar.vue')['default']
    ExpenseListMain: typeof import('./src/components/page/Account/ExpenseList/ExpenseListMain.vue')['default']
    ExpenseListModal: typeof import('./src/components/page/Account/ExpenseList/ExpenseListModal.vue')['default']
    ExpenseListSearch: typeof import('./src/components/page/Account/ExpenseList/ExpenseListSearch.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LeftManuBar: typeof import('./src/components/common/LeftManuBar.vue')['default']
    LoginMain: typeof import('./src/components/page/Login/LoginMain.vue')['default']
    ManageMain: typeof import('./src/components/page/Account/Manage/ManageMain.vue')['default']
    ManageModal: typeof import('./src/components/page/Account/Manage/ManageModal.vue')['default']
    ManageSearch: typeof import('./src/components/page/Account/Manage/ManageSearch.vue')['default']
    MonthlyClientModal: typeof import('./src/components/page/Sales/Monthly/MonthlyClientModal.vue')['default']
    MonthlyMain: typeof import('./src/components/page/Sales/Monthly/MonthlyMain.vue')['default']
    MonthlyProductModal: typeof import('./src/components/page/Sales/Monthly/MonthlyProductModal.vue')['default']
    MonthlySearch: typeof import('./src/components/page/Sales/Monthly/MonthlySearch.vue')['default']
    NoticeMain: typeof import('./src/components/page/System/Notice/NoticeMain.vue')['default']
    NoticeModal: typeof import('./src/components/page/System/Notice/NoticeModal.vue')['default']
    NoticeSearch: typeof import('./src/components/page/System/Notice/NoticeSearch.vue')['default']
    Pagination: typeof import('./src/components/common/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalaryListMain: typeof import('./src/components/page/personnel/Salary-list/SalaryListMain.vue')['default']
    SalaryListModal: typeof import('./src/components/page/personnel/Salary-list/SalaryListModal.vue')['default']
    SalaryListSearch: typeof import('./src/components/page/personnel/Salary-list/SalaryListSearch.vue')['default']
    SalesDetailModal: typeof import('./src/components/page/Business/Plan/SalesDetailModal.vue')['default']
    SalesPlanMain: typeof import('./src/components/page/Business/Plan/SalesPlanMain.vue')['default']
    SalesPlanSearch: typeof import('./src/components/page/Business/Plan/SalesPlanSearch.vue')['default']
    SalesRegisterModal: typeof import('./src/components/page/Business/Plan/SalesRegisterModal.vue')['default']
  }
}
